[Sprint 22 / PD-50] - [Feature] Add implementation GRPC
ichiro-its/aruku_interfaces pull request #5
Opened 2023-08-07 10:55 UTC by marfanr

## Jira Link: 
https://ichiro-its.atlassian.net/browse/PD-50?atlOrigin=eyJpIjoiYzAxZWU5MzYxMGQwNDQ0ZWE3MjY2ZDQxMDg2MzdhYmEiLCJwIjoiaiJ9

## Description

added protobuf config for grpc

## Type of Change

- [ ] Bugfix
- [ ] Enhancement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [x] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2023-11-06 16:40 UTC, threeal requested changes

2023-11-06 16:40 UTC, threeal commented on CMakeLists.txt
> +  ${_PROTOBUF_LIBPROTOBUF}
We can just put the libraries here:
```suggestion
  gRPC::grpc++_reflection
  gRPC::grpc++
  protobuf::libprotobuf
```

2023-11-06 16:40 UTC, threeal commented on CMakeLists.txt
> +      COMMAND ${_PROTOBUF_PROTOC}
We can just use `$<TARGET_FILE:protobuf::protoc>` here:
```suggestion
      COMMAND $<TARGET_FILE:protobuf::protoc>
```

2023-11-06 16:40 UTC, threeal commented on CMakeLists.txt
> +        --plugin=protoc-gen-grpc="${_GRPC_CPP_PLUGIN_EXECUTABLE}"
We can just use `$<TARGET_FILE:gRPC::grpc_cpp_plugin>` in here:
```suggestion
        --plugin=protoc-gen-grpc=$<TARGET_FILE:gRPC::grpc_cpp_plugin>
```

2023-11-06 16:40 UTC, threeal commented on CMakeLists.txt
> +get_filename_component(aruku_proto "./proto/aruku.proto" ABSOLUTE)
Much accurate:
```suggestion
set(aruku_proto ${CMAKE_CURRENT_SOURCE_DIR}/proto/aruku.proto)
```

2023-11-06 16:40 UTC, threeal commented on CMakeLists.txt
> +get_filename_component(aruku_proto_path "${aruku_proto}" PATH)
Please use `DIRECTORY`, see [this](https://cmake.org/cmake/help/latest/command/get_filename_component.html).
```suggestion
get_filename_component(aruku_proto_path "${aruku_proto}" DIRECTORY)
```

2023-11-06 16:40 UTC, threeal commented on CMakeLists.txt
> +  ${${CMAKE_CURRENT_BINARY_DIR}/aruku.grpc.pb.h})
Why there's double `${}` in here? Won't it work?

```suggestion
  ${CMAKE_CURRENT_BINARY_DIR}/aruku.pb.cc
  ${CMAKE_CURRENT_BINARY_DIR}/aruku.pb.h
  ${CMAKE_CURRENT_BINARY_DIR}/aruku.pb.h
  ${CMAKE_CURRENT_BINARY_DIR}/aruku.grpc.pb.h)
```

2024-01-17 05:41 UTC, threeal approved these changes

2024-05-29 13:33 UTC, FaaizHaikal approved these changes

2024-06-05 13:12 UTC, merged